spring:
  h2.console:
    enabled: true
    path: /h2

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true


---

spring:
  profiles: devh2file

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://192.168.56.1:9095/file:~/lab
    username: sa
    password:
---

spring:
  profiles: devhpsql

  jpa:
    database: PostgreSQL

  datasource:
    url: jdbc:postgresql://localhost:5432/desenv?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: postgres